---
- name: Install basic pages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tzdata
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-docker
    - python3-mysqldb
    - mysql-server
- name: "Create database"
  mysql_db: 
    name: "{{ mysql_db }}"
- name: "Create user"
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_passwd }}"
    priv: "*.*:ALL"
    host: '{{ mysql_host_ip }}'
- name: copy my.cnf
  copy:
    src: my.cnf
    dest: /etc/mysql/
    mode: '0644'