---
- name: Install basic pages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-docker
    - mysql-client
- name: Download docker package 
  get_url:
    url: "{{ docker_package_path }}"
    dest: "{{ docker_dest_path }}"
- name: Download docker compose
  apt:
    name: docker-compose
    state: present
- name: check apt source
  apt_repository: 
    repo: "{{ docker_repo_path }}"
    state: present
- name: Install docker page
  apt:
    name: docker-ce
    state: present
- name: create build directory 
  file:
    path: /simon/demo-dockerfile
    state: directory
    mode: '0755'
- name: copy Front
  copy:
    src: /home/simon/Desktop/PROGRAMS/ansible_yml/application/front/
    dest: /simon/demo-dockerfile/
- name: copy Dockerfile
  copy:
    src: front/Dockerfile
    dest: /simon/demo-dockerfile/Dockerfile
    mode: '0644'
- name: copy Docker-compose
  copy:
    src: front/docker-compose.yml
    dest: /simon/demo-dockerfile/docker-compose.yml
    mode: '0644'
- name: copy Backend
  copy:
    src: /home/simon/Desktop/PROGRAMS/ansible_yml/application/back
    dest: /simon/
- name: copy Dockerfile
  copy:
    src: back/Dockerfile
    dest: /simon/back/Dockerfile
    mode: '0644'
- name: copy Docker-compose
  copy:
    src: back/docker-compose.yml
    dest: /simon/back/docker-compose.yml
    mode: '0644'
- name: copy dump_sql script
  copy:
    src: back/dump_sql.sh
    dest: /simon/dump_sql.sh
    mode: '0644'
- name: Create crontab for sql dump
  ansible.builtin.cron: 
    name: "run sql dump every day"
    minute: "0"
    hour: "20"
    job: "sh /simon/dump_sql.sh"
    user: root
    cron_file: sql_dump_cron
- name: Build container front
  become: True
  shell:
    cmd: "docker-compose build"
    chdir: /simon/demo-dockerfile/
- name: Run container front
  become: True
  shell:
    cmd: "docker-compose up -d"
    chdir: /simon/demo-dockerfile/
- name: Build container back
  become: True
  shell:
    cmd: "docker-compose build"
    chdir: /simon/back/
- name: Run container back
  become: True
  shell:
    cmd: "docker-compose up -d"
    chdir: /simon/back/